version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
volumes:
  db: