name: CI - Run Tests via Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  start_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        run: |
          cp delivery_app/env.example delivery_app/.env
          cp register_app/env.example register_app/.env
          cp ./env.example ./.env
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        run: |
          docker compose -f docker-compose.test.yaml up --build --exit-code-from tests
      - name: Tear down containers
        if: always()
        run: docker compose -f docker-compose.test.yaml down --volumes